<a href="https://colab.research.google.com/github/chaitu-im/eda-lab-experiment/blob/main/exp-4.28_07_2-26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
data = np.arange(15, 30).reshape(5, 3)
dfx = pd.DataFrame(data, index=['Virat Kohli', 'MS Dhoni', 'Rohit Sharma',
                                'KL Rahul', 'Sachin Tendulkar'],
                         columns=['IPL_2021', 'IPL_2022', 'IPL_2023'])
dfx

                  IPL_2021  IPL_2022  IPL_2023
Virat Kohli             15        16        17
MS Dhoni                18        19        20
Rohit Sharma            21        22        23
KL Rahul                24        25        26
Sachin Tendulkar        27        28        29

In [ ]:
dfx['IPL_2024'] = np.nan
dfx.loc['Jasprit Bumrah'] = pd.Series(np.arange(15, 19), index=dfx.columns[:4])
dfx.loc['Hardik Pandya'] = np.nan
dfx['IPL_2025'] = np.nan
dfx.loc['Virat Kohli', 'IPL_2024'] = 20.
dfx

                  IPL_2021  IPL_2022  IPL_2023  IPL_2024  IPL_2025
Virat Kohli           15.0      16.0      17.0      20.0       NaN
MS Dhoni              18.0      19.0      20.0       NaN       NaN
Rohit Sharma          21.0      22.0      23.0       NaN       NaN
KL Rahul              24.0      25.0      26.0       NaN       NaN
Sachin Tendulkar      27.0      28.0      29.0       NaN       NaN
Jasprit Bumrah        15.0      16.0      17.0      18.0       NaN
Hardik Pandya          NaN       NaN       NaN       NaN       NaN

In [ ]:
dfx.isnull()

                  IPL_2021  IPL_2022  IPL_2023  IPL_2024  IPL_2025
Virat Kohli          False     False     False     False      True
MS Dhoni             False     False     False      True      True
Rohit Sharma         False     False     False      True      True
KL Rahul             False     False     False      True      True
Sachin Tendulkar     False     False     False      True      True
Jasprit Bumrah       False     False     False     False      True
Hardik Pandya         True      True      True      True      True

In [ ]:
dfx.notnull()

                  IPL_2021  IPL_2022  IPL_2023  IPL_2024  IPL_2025
Virat Kohli           True      True      True      True     False
MS Dhoni              True      True      True     False     False
Rohit Sharma          True      True      True     False     False
KL Rahul              True      True      True     False     False
Sachin Tendulkar      True      True      True     False     False
Jasprit Bumrah        True      True      True      True     False
Hardik Pandya        False     False     False     False     False

In [ ]:
dfx.isnull().sum()

IPL_2021    1
IPL_2022    1
IPL_2023    1
IPL_2024    5
IPL_2025    7
dtype: int64

In [ ]:
dfx.isnull().sum().sum()

np.int64(15)

In [ ]:
dfx.count()

IPL_2021    6
IPL_2022    6
IPL_2023    6
IPL_2024    2
IPL_2025    0
dtype: int64

In [ ]:
dfx.IPL_2024[dfx.IPL_2024.notnull()]

Virat Kohli       20.0
Jasprit Bumrah    18.0
Name: IPL_2024, dtype: float64

In [ ]:
dfx.IPL_2024.dropna()

Virat Kohli       20.0
Jasprit Bumrah    18.0
Name: IPL_2024, dtype: float64

In [ ]:
dfx.dropna()

Empty DataFrame
Columns: [IPL_2021, IPL_2022, IPL_2023, IPL_2024, IPL_2025]
Index: []

In [ ]:
dfx.dropna(how='all')

                  IPL_2021  IPL_2022  IPL_2023  IPL_2024  IPL_2025
Virat Kohli           15.0      16.0      17.0      20.0       NaN
MS Dhoni              18.0      19.0      20.0       NaN       NaN
Rohit Sharma          21.0      22.0      23.0       NaN       NaN
KL Rahul              24.0      25.0      26.0       NaN       NaN
Sachin Tendulkar      27.0      28.0      29.0       NaN       NaN
Jasprit Bumrah        15.0      16.0      17.0      18.0       NaN

In [ ]:
dfx.dropna(how='all', axis=1)

                  IPL_2021  IPL_2022  IPL_2023  IPL_2024
Virat Kohli           15.0      16.0      17.0      20.0
MS Dhoni              18.0      19.0      20.0       NaN
Rohit Sharma          21.0      22.0      23.0       NaN
KL Rahul              24.0      25.0      26.0       NaN
Sachin Tendulkar      27.0      28.0      29.0       NaN
Jasprit Bumrah        15.0      16.0      17.0      18.0
Hardik Pandya          NaN       NaN       NaN       NaN

In [ ]:
dfx.dropna(thresh=5, axis=1)

                  IPL_2021  IPL_2022  IPL_2023
Virat Kohli           15.0      16.0      17.0
MS Dhoni              18.0      19.0      20.0
Rohit Sharma          21.0      22.0      23.0
KL Rahul              24.0      25.0      26.0
Sachin Tendulkar      27.0      28.0      29.0
Jasprit Bumrah        15.0      16.0      17.0
Hardik Pandya          NaN       NaN       NaN

In [30]:
ar1 = np.array([100, 200, np.nan, 300])
ser1 = pd.Series(ar1)
ar1.mean(),ser1.mean()

(np.float64(nan), np.float64(200.0))

In [33]:
ser2 = dfx.IPL_2024
ser2.sum()
ser2.mean()

np.float64(19.0)

In [34]:
ser2.cumsum()

Virat Kohli         20.0
MS Dhoni             NaN
Rohit Sharma         NaN
KL Rahul             NaN
Sachin Tendulkar     NaN
Jasprit Bumrah      38.0
Hardik Pandya        NaN
Name: IPL_2024, dtype: float64

In [35]:
filledDf = dfx.fillna(0)
filledDfdfx.mean()
filledDf.mean()

                  IPL_2021  IPL_2022  IPL_2023  IPL_2024  IPL_2025
Virat Kohli           15.0      16.0      17.0      20.0       0.0
MS Dhoni              18.0      19.0      20.0       0.0       0.0
Rohit Sharma          21.0      22.0      23.0       0.0       0.0
KL Rahul              24.0      25.0      26.0       0.0       0.0
Sachin Tendulkar      27.0      28.0      29.0       0.0       0.0
Jasprit Bumrah        15.0      16.0      17.0      18.0       0.0
Hardik Pandya          0.0       0.0       0.0       0.0       0.0

In [36]:
dfx.mean()
filledDf.mean()

IPL_2021    17.142857
IPL_2022    18.000000
IPL_2023    18.857143
IPL_2024     5.428571
IPL_2025     0.000000
dtype: float64

In [37]:
dfx['IPL_2024'].ffill()

Virat Kohli         20.0
MS Dhoni            20.0
Rohit Sharma        20.0
KL Rahul            20.0
Sachin Tendulkar    20.0
Jasprit Bumrah      18.0
Hardik Pandya       18.0
Name: IPL_2024, dtype: float64

In [38]:
dfx['IPL_2024'].bfill()

Virat Kohli         20.0
MS Dhoni            18.0
Rohit Sharma        18.0
KL Rahul            18.0
Sachin Tendulkar    18.0
Jasprit Bumrah      18.0
Hardik Pandya        NaN
Name: IPL_2024, dtype: float64